version: '3.9'

services:
  microservice:
    image: microservice-starter
    build:
      context: ./
    container_name: microservice-starter
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - 5001:80
    cap_add:
      - SYS_ADMIN

